bfs: bfs.c
	gcc -o bfs bfs.c -std=c99
run_bfs: bfs
	./bfs
bfs_omp:bfs_omp.c
	gcc -O3 -o bfs_omp bfs_omp.c -fopenmp -std=c99 
run_bfs_omp: bfs_omp
	./bfs_omp
dfs: dfs.c
	gcc -o dfs dfs.c -std=c99
run_dfs: dfs
	./dfs
